// Generated by CoffeeScript 1.4.0
(function() {
  var argv, client, doc, filename, fs, timeout, write;

  client = require('share').client;

  fs = require('fs');

  argv = require('optimist').usage('Usage: $0 -d docname [--url URL] [-f padDB.txt]')["default"]('d', 'doc1')["default"]('url', '127.0.0.1:5000/pad.html').argv;

  //filename = argv.f || argv.d;
  filename = 'padDB.txt'; //for persistence

  console.log("Opening '" + argv.d + "' at " + argv.url + ". Saving to '" + filename + "'");

  timeout = null;

  doc = null;

  write = function() {
    if (timeout === null) {
      return timeout = setTimeout(function() {
        console.log("Saved version " + doc.version);
        fs.writeFile(filename, doc.snapshot);
        return timeout = null;
      }, 1000);
    }
  };

  client.open(argv.d, 'text', argv.url, function(error, d) {
    doc = d;
    console.log('Document ' + argv.d + ' open at version ' + doc.version);
    write();
    return doc.on('change', function(op) {
      return write();
    });
  });

}).call(this);
